import type { LucideIcon } from 'lucide-react'
import {
  ShoppingCart,
  UtensilsCrossed,
  Bus,
  Car,
  Home,
  Zap,
  Droplets,
  Wifi,
  Smartphone,
  Film,
  Music,
  Gamepad2,
  Dumbbell,
  HeartPulse,
  Shirt,
  Plane,
  GraduationCap,
  Gift,
  PawPrint,
  Baby,
  Coffee,
  CreditCard,
  PiggyBank,
  Package,
} from 'lucide-react'

// Curated icon set offered when creating/editing a category.
// The icon name is what gets persisted in Category.icon.
export const CATEGORY_ICON_OPTIONS: Array<{ name: string; label: string; Icon: LucideIcon }> = [
  { name: 'shopping-cart', label: 'Compra', Icon: ShoppingCart },
  { name: 'utensils', label: 'Restaurantes', Icon: UtensilsCrossed },
  { name: 'bus', label: 'Transporte', Icon: Bus },
  { name: 'car', label: 'Coche', Icon: Car },
  { name: 'home', label: 'Hogar', Icon: Home },
  { name: 'zap', label: 'Luz', Icon: Zap },
  { name: 'droplets', label: 'Agua', Icon: Droplets },
  { name: 'wifi', label: 'Internet', Icon: Wifi },
  { name: 'smartphone', label: 'Móvil', Icon: Smartphone },
  { name: 'film', label: 'Cine', Icon: Film },
  { name: 'music', label: 'Música', Icon: Music },
  { name: 'gamepad', label: 'Videojuegos', Icon: Gamepad2 },
  { name: 'dumbbell', label: 'Gimnasio', Icon: Dumbbell },
  { name: 'heart-pulse', label: 'Salud', Icon: HeartPulse },
  { name: 'shirt', label: 'Ropa', Icon: Shirt },
  { name: 'plane', label: 'Viajes', Icon: Plane },
  { name: 'graduation-cap', label: 'Educación', Icon: GraduationCap },
  { name: 'gift', label: 'Regalos', Icon: Gift },
  { name: 'paw-print', label: 'Mascotas', Icon: PawPrint },
  { name: 'baby', label: 'Bebé', Icon: Baby },
  { name: 'coffee', label: 'Café', Icon: Coffee },
  { name: 'credit-card', label: 'Préstamos', Icon: CreditCard },
  { name: 'piggy-bank', label: 'Ahorro', Icon: PiggyBank },
  { name: 'package', label: 'Otros', Icon: Package },
]

